proxy:
  image: evanshunt/nginx-ssl-proxy
  ports:
  - "443:443"
  links:
  - "web"
  
web:
  image: evanshunt/php-for-ss:4
  volumes:
  - ./src:/var/www/html/
  - ./vendor:/var/www/vendor
  - ./config:/var/www/config
  - ./.env:/var/www/.env
  - ./wp-cli.yml:/var/www/wp-cli.yml
  ports:
  - "80:80"
  links:
  - "database"

database:
  image: mysql/mysql-server:5.7
  volumes:
  - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
  ports:
  - "3306:3306"
  - "3307:3307"
  environment:
  - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
  - MYSQL_USER=$DB_USER
  - MYSQL_PASSWORD=$DB_PASSWORD
  - MYSQL_DATABASE=$DB_NAME