@include('components.banner', $component_banner)
@include('components.content-block')
@include('components.embed-map', $component_embed_map)
@include('components.contact-form', $component_contact_form)
@include('components.panel-menu', $component_panel_menu)
@include('components.full-width-panel', $component_full_width_panel)
