@include('components.banner', $component_banner)
@include('components.content-block')
@include('components.featured-panel', $component_featured_panel_one)
@include('components.featured-panel', $component_featured_panel_two)
@include('components.featured-panel', $component_featured_panel_three)
@include('components.full-width-panel', $component_full_width_panel)
